### ISSUE TITLE
Command `w3m-scroll-up-or-next-url` behaves the same as `w3m-scroll-down-or-previous-url`

### ISSUE THREAD

**Issue by pegzmasta** [Boruch-Baum/emacs-w3m#1]
The source code for command `w3m-scroll-up-or-next-url` is identical to `w3m-scroll-down-or-previous-url`.  This causes the keybinding **SPC** to behave the same way as keybinding **DEL** - i.e., these commands always bring me to the previous url instead of the next url.

I noticed this behaviour when I was browsing through the [gemini archives](https://lists.orbitalfox.eu/archives/gemini/2020/thread.html) (open any of those threads to test this behaviour).

Should the [defun on this repository](https://github.com/Boruch-Baum/emacs-w3m/blob/master/w3m.el#L8825) match the [definition on the main branch](https://github.com/emacs-w3m/emacs-w3m/blob/master/w3m.el#L9064)?

**Comment by Boruch-Baum** [comment]
Yes. It's another merge bug from the monster commit. Fixed. Thanks.
