### ISSUE TITLE
File mime-w3m.el has strange strings that prevent it from functioning.

### ISSUE THREAD

**Issue by pegzmasta** [Boruch-Baum/emacs-w3m#2]
Hi.

I don't know how this happened (perhaps a version control bug?), but I see strange strings within the file _mime-w3m.el_, which look something like this:

`<<<<<<< HEAD`
`=======`
`>>>>>>> b5ec8774904ac9be0879928283b99ac77c3e2b63`

The last string appears to be a reference to commit b5ec8774904ac9be0879928283b99ac77c3e2b63 (_mime-w3m.el_ looks fine in this commit; no strange strings).

Attached is a patch - [mime-w3m-patch.txt](https://github.com/Boruch-Baum/emacs-w3m/files/4952005/mime-w3m-patch.txt) - to show the difference of the file on your branch and the main branch.

**Comment by Boruch-Baum** [comment]
Thanks. Fixed. I didn't notice it because I've been testing a merge branch for a monster upstream commit. The fix matches my testing branch.
